import { petRouter } from './Pet.js';
import { consumableRouter } from './Consumable.js';
import { equipmentRouter } from './Equipment.js'
import { harnessRouter } from './Harness.js';
import { idolRouter } from './Idol.js';
import { resourceRouter } from './Resource.js';
import { setRouter } from './Set.js';
import { weaponRouter } from './Weapon.js';
import { monsterRouter } from './Monster.js';
import { mountRouter } from './mount.js';
